import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        {/* <link rel="shortcut icon" href={`${process.env.basePath}/icon/favicon.ico`} /> */}
        <link href="mncsek/assets/vendor/aos/aos.css" rel="stylesheet" />
        <link href="mncsek/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
        <link href="mncsek/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet" />
        <link href="mncsek/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet" />
        <link href="mncsek/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet" />
        <link href="mncsek/assets/vendor/remixicon/remixicon.css" rel="stylesheet" />
        <link href="mncsek/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet" />
        <link href="mncsek/assets/css/style.css" rel="stylesheet" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
